# Site settings
brand: Mark Grindy
title: Mark Grindy - Writer for Hire
email: mark@markgrindy.com
url: https://markgrindy.com
description: "You've got a big idea. Let's work together to get it ready for primetime."
keywords: "Ebook Writing, Line Editing, Copy Editing, Editing, Proofreading, Speech Writing, Speechwriting, Blog Development, RFP Writing, Writing, Speeches,
Book Writing, Blog Writing, Ghostwriting, Book Editing, Toast Speech, Editorial Writing"
offering: 'Collaborative executive communications consulting, specializing in speeches, opinion pieces, and stategic narratives.'
skills: 'Research. Writing. Editing.'
meta_author: Grindy Mark

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static
# if using formspree.io, enter the form's endpoint here:
formspree: https://formspree.io/f/xyyagabl


# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 002c45 # a:hover, hero bg, about bg, button color
  primary-rgb: "34,34,34" # portfolio item hover
  secondary: 007cc3 # nav bg
  secondary-dark: 398bb9 # nav current section bg, (c)

# Footer settings (to remove section from site, simply leave value blank)
footer:
  copyright: 'Mark Grindy'
  address:
  social:

# Postal address (add as many lines as necessary)
address:
  - line: ''

# Proofpoints
proofpoint-heading: "What they've said"
proofpoint-tagline: "As your writing partner, Mark brings high-level experience from the C-suite and the presidential campaign trail. Here's what clients and colleagues have said about his work:"
proofpoints:
  - quote: '"You are the team behind the team that makes me look good." —Fortune 500 CEO'
  - quote: '"Wow. I&#39;m a regular Bill Shakespeare! ;) Thx for making me sound compelling." —Partner in nine-figure venture funds'
  - quote: '"So fun, Mark! You guys are major pros. Such a pleasure working with you" —Creator and host of multiple top national radio shows and podcasts'
  - quote: '"AMAZING hire." —U.S. Senate speechwriter.'
  - quote: '"The ending had me in tears." —Vice Presidential speechwriter'
  - quote: '"Mark, you are channeling me—these edits are equal parts sharp and snarky, and they&#39;re all right on." —Presidential speechwriter'

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/#
  # - title: instagram
  #   url: http://instagram.com/#
  - title: linkedin
    url: https://www.linkedin.com/in/markgrindy/

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
